_LABELS_28 = [
    "Grab(1)",
    "Grab(2)",
    "Tap(1)",
    "Tap(2)",
    "Expand(1)",
    "Expand(2)",
    "Pinch(1)",
    "Pinch(2)",
    "Rotate Clockwise(1)",
    "Rotate Clockwise(2)",
    "Rotate Counter Clockwise(1)",
    "Rotate Counter Clockwise(2)",
    "Swipe Right(1)",
    "Swipe Right(2)",
    "Swipe Left(1)",
    "Swipe Left(2)",
    "Swipe Up(1)",
    "Swipe Up(2)",
    "Swipe Down(1)",
    "Swipe Down(2)",
    "Swipe X(1)",
    "Swipe X(2)",
    "Swipe +(1)",
    "Swipe +(2)",
    "Swipe V(1)",
    "Swipe V(2)",
    "Shake(1)",
    "Shake(2)",
]

_LABELS_14 = [
    "Grab",
    "Tap",
    "Expand",
    "Pinch",
    "Rotate Clockwise",
    "Rotate Counter Clockwise",
    "Swipe Right",
    "Swipe Left",
    "Swipe Up",
    "Swipe Down",
    "Swipe X",
    "Swipe +",
    "Swipe V",
    "Shake",
]
